/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import sk.tomas.neural.Util;

import java.util.Random;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {

        double[] array = new double[]{1, 2, 3, 4, 1, 2, 3};
        for (int i = 0; i < array.length; i++) {
            array[i] = Math.exp(array[i]);
        }
        double sum = 0;
        for (double v : array) {
            sum += v;
        }
        for (int i = 0; i < array.length; i++) {
            array[i] = array[i] / sum;
        }
        for (double v : array) {
            System.out.print(v + " ");
        }
    }

    @Test
    public void lnTest() {
        double l = 0.619;
        double result = Math.log(l);
        System.out.println(result);
    }

    @Test
    public void sigmoidTest() {
        Random random = new Random();
        //double input = random.nextDouble();
        double input = 0.3925;
        System.out.println(input);
        double sigmoid = Util.sigmoid(input);
        System.out.println(sigmoid);
        double derivate = Util.sigmoidDerivate(sigmoid);
        System.out.println(derivate);
    }

    @Test
    public void errorAffectTest() {
        double result = Util.errorAffect(0.01, 0.75136507, 0.596884378);
        result = Util.calculateNewWeight(0.45, 0.5, result);
        System.out.println(result);
    }

}
