/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {

        double[] array = new double[]{1, 2, 3, 4, 1, 2, 3};
        for (int i = 0; i < array.length; i++) {
            array[i] = Math.exp(array[i]);
        }
        double sum = 0;
        for (double v : array) {
            sum += v;
        }
        for (int i = 0; i < array.length; i++) {
            array[i] = array[i] / sum;
        }
        for (double v : array) {
            System.out.print(v + " ");
        }
    }

    @Test
    public void lnTest() {
        double l = 0.619;
        double result = Math.log(l);
        System.out.println(result);
    }

}
